const LEAD_TYPES = {
  GENERAL_ENQUIRY: "GENERAL_ENQUIRY",

  QUOTE_REQUEST: "QUOTE_REQUEST",

  EXPERT_CONSULTATION: "EXPERT_CONSULTATION",

  PRODUCT_ENQUIRY: "PRODUCT_ENQUIRY",

  BULK_ORDER: "BULK_ORDER",

  CUSTOM_PRINTING: "CUSTOM_PRINTING",

  DESIGN_ASSISTANCE: "DESIGN_ASSISTANCE",

  CALLBACK_REQUEST: "CALLBACK_REQUEST",

  ORDER_REQUEST: "ORDER_REQUEST",
};

export default LEAD_TYPES;
